CREATE SCHEMA x DEFAULT CHARACTER SET utf8;

CREATE TABLE x.users (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  username VARCHAR(25) NOT NULL,
  enabled TINYINT(1) UNSIGNED NOT NULL,
  createdDate DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX username_UNIQUE (username ASC));
