CREATE SCHEMA x DEFAULT CHARACTER SET utf8;

CREATE TABLE x.users (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  username VARCHAR(25) NOT NULL,
  enabled TINYINT UNSIGNED NOT NULL DEFAULT 1,
  createdDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE INDEX username_UNIQUE (username ASC));
